backend:
  # name: test-repo
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

display_url: https://webhart-base.netlify.com

collections:
  - name: posts
    label: Blog
    label_singular: Post
    folder: src/content/posts/
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - {
          name: templateKey,
          label: Template Key,
          widget: hidden,
          default: post,
        }
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image, required: false }
      - { name: body, labal: Content, widget: markdown }