backend:
  # name: test-repo
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

display_url: https://webhart-base.netlify.com

collections:
  - name: leveranciers
    label: Leveranciers
    label_singular: leverancier
    folder: src/content/leveranciers/
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - {
          name: templateKey,
          label: Template Key,
          widget: hidden,
          default: leverancier,
        }
      - { name: name, label: Name, widget: string }
      - { name: site, label: Site, widget: string }
      - { name: featured, label: Uitgelicht, widget: boolean, default: true }
      - { name: image, label: Image, widget: image, required: false }
  # - name: posts
  #   label: Blog
  #   label_singular: Post
  #   folder: src/content/posts/
  #   create: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - {
  #         name: templateKey,
  #         label: Template Key,
  #         widget: hidden,
  #         default: post,
  #       }
  #     - { name: title, label: Title, widget: string }
  #     - { name: date, label: Date, widget: datetime }
  #     - { name: image, label: Image, widget: image, required: false }
  #     - { name: body, labal: Content, widget: markdown }
