backend:
  # name: test-repo
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

display_url: https://lodeco-eeckhout.be

collections:
  # - name: leveranciers
  #   label: Leveranciers
  #   label_singular: leverancier
  #   folder: src/content/leveranciers/
  #   create: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   preview: false
  #   fields:
  #     - {
  #         name: templateKey,
  #         label: Template Key,
  #         widget: hidden,
  #         default: leverancier,
  #       }
  #     - { name: title, label: Naam, widget: string }
  #     - { name: site, label: Site, widget: string }
  #     - { name: featured, label: Uitgelicht, widget: boolean, default: true }
  #     - { name: image, label: Afbeelding, widget: image, required: false }
  - name: deliflash
    label: Deli Flash
    folder: src/content/deliflash/
    create: true
    slug: '{{year}}-{{month}}-{{day}}'
    preview: false
    fields:
      - {
          name: templateKey,
          label: Template Key,
          widget: hidden,
          default: deliflash,
        }
      - { name: title, label: Naam, widget: string }
      - { name: date, label: Datum, widget: date, format: 'YYYY-MM-DD' }
      - { name: image, label: Afbeelding, widget: image, required: false }
      - { label: 'PDF', name: 'pdf', widget: 'file' }
  # - name: posts
  #   label: Blog
  #   label_singular: Post
  #   folder: src/content/posts/
  #   create: true
  #   slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
  #   fields:
  #     - {
  #         name: templateKey,
  #         label: Template Key,
  #         widget: hidden,
  #         default: post,
  #       }
  #     - { name: title, label: Title, widget: string }
  #     - { name: date, label: Date, widget: datetime }
  #     - { name: image, label: Image, widget: image, required: false }
  #     - { name: body, labal: Content, widget: markdown }
